### ISSUE TITLE
Error while launching simmultihusky.launch

### ISSUE THREAD

**Issue by sbt9548** [bsb808/nre_simmultihusky#1]
Hello,
I have been trying to run this package. however im facing an issue while running simmultihusky.launch i am able to launch the other files but not this. Please help . this is the error i keep getting.  im sorry, im very new to ROS and trying to work on this package 

````
st@st-HP-Notebook:~$ roslaunch nre_simmultihusky simmultihusky.launch
... logging to /home/st/.ros/log/cfe0359c-b60c-11e6-aa27-c8ff287cb4b0/roslaunch-st-HP-Notebook-12854.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 687, in main
    process_includes(doc, os.path.dirname(args[0]))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 271, in process_includes
    raise XacroException("included file \"%s\" could not be opened: %s" % (filename, str(e)))
xacro.XacroException: included file "/home/st/indigo_ws/src/nre_simmultihusky/xacro/h1.gazebo.xacro" could not be opened: [Errno 2] No such file or directory: '/home/st/indigo_ws/src/nre_simmultihusky/xacro/h1.gazebo.xacro'
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/home/st/indigo_ws/src/nre_simmultihusky/xacro/mydesc.gazebo.xacro'  laser_enabled:=true  ur5_enabled:=false  kinect_enabled:=false  prefix:=h1  ] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py '$(find nre_simmultihusky)/xacro/mydesc.gazebo.xacro'  laser_enabled:=$(arg laser_enabled)  ur5_enabled:=$(arg ur5_enabled)  kinect_enabled:=$(arg kinect_enabled)  prefix:=$(arg ns1)  " name="robot_description"/>
The traceback for the exception was written to the log file
````

thanks,

Sonam.

**Comment by bsb808** [comment]
Sonam,

The simmultihusky.launch is an older version that I should probably remove from the archive.  Try running this...

`
roslaunch nre_simmultihusky multihusky.launch 
`

Brian

**Comment by dmorozin** [comment]
im getting this error when trying to launch `roslaunch nre_simmultihusky multihusky.launch`. Can you tell me whats the problem? I haven't modified anything.

```
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
deprecated: xacro tags should be prepended with 'xacro' xml namespace.
Use the following script to fix incorrect usage:
        find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
when processing file: /home/dodo/catkin_ws/src/nre_simmultihusky/xacro/mhusky.gazebo.xacro

unknown macro name: xacro:husky_robot_gazebo None None
when processing file: /home/dodo/catkin_ws/src/nre_simmultihusky/xacro/mhusky.gazebo.xacro
while processing /home/dodo/catkin_ws/src/nre_simmultihusky/launch/husky.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/share/xacro/xacro.py '/home/dodo/catkin_ws/src/nre_simmultihusky/xacro/mhusky.gazebo.xacro'         laser_enabled:=true         ur5_enabled:=false         kinect_enabled:=false         nsp:=h1         tfpre:=h1_tf         ] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro.py '$(find nre_simmultihusky)/xacro/mhusky.gazebo.xacro'         laser_enabled:=$(arg laser_enabled)         ur5_enabled:=$(arg ur5_enabled)         kinect_enabled:=$(arg kinect_enabled)         nsp:=$(arg namespace)         tfpre:=$(arg tfpre)         " name="robot_description"/>
The traceback for the exception was written to the log file
```

**Comment by TONG369** [comment]
Have you solved your problem? I met exactly the same problem as you? If so, please contact me, thank you very much~~~
